"use client";
import { useState } from "react";
import Link from "next/link";
import { Card } from "@/components/ui/primitives";
import { useJson, type LiveState } from "@/lib/use-live";
import type { DomainLiveBundle } from "@/lib/live";
import type { ActionData } from "@/lib/action-queue";
import { actionDestination } from "@/lib/action-queue";
import type { SiteCommand } from "@/lib/command-model";
import { SiteFindingWorkDrawer, type SiteFinding } from "@/components/workflow/site-finding-work-drawer";
import { stamp } from "./shared";
import type { PortfolioLive } from "@/lib/live";

export function PortfolioDataHealth({ data }: { data?: PortfolioLive | null }) {
  if (!data) return null;
  const missing = data.domains.filter((site) => site.searchPeriod?.clicks == null || site.health == null);
  return <details className="rounded-lg border border-border bg-card px-4 py-3"><summary className="cursor-pointer text-sm font-semibold">Portfolio data health <span className="ml-2 font-normal text-muted">{data.domains.length - missing.length}/{data.domains.length} websites have search and audit results</span></summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.domains.map((site) => <Link key={site.domainId} href={`/health?site=${site.domainId}`} className="rounded-md border border-border p-3 text-sm"><strong>{site.domainId}</strong><span className="mt-1 block text-xs text-muted">Search {site.searchPeriod?.clicks == null ? "missing" : `through ${site.searchPeriod.end}`} · Audit {site.health == null ? "missing" : "saved"}</span><span className="mt-1 block text-xs text-purple">Review source freshness and recovery →</span></Link>)}</div></details>;
}

export function DataHealthSummary({ site }: { site: string }) {
  const state = useJson<SiteCommand>(`/api/command?site=${encodeURIComponent(site)}`);
  const rows = state.data?.health ?? [], attention = rows.filter((row) => row.state !== "ready").length;
  const speed = state.data?.records.find((row) => row.kind === "speed" && row.status === "completed");
  return <details className="rounded-lg border border-border bg-card px-4 py-2.5"><summary className="cursor-pointer text-sm font-semibold">Data health <span className="ml-2 font-normal text-muted">{state.error ? "Status unavailable" : !state.data ? "Loading…" : attention ? `${attention} sources need attention` : "All tracked sources have recent saved data"}</span></summary><div className="mt-3 grid gap-3 border-t border-border pt-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map((row) => <Link key={row.id} href={row.href} className="text-sm"><strong>{row.label}</strong><span className="ml-2 text-muted">{row.state.replace(/_/g, " ")}</span><span className="mt-1 block text-xs text-muted">Collected {stamp(row.updatedAt)} · data through {row.through ?? "unavailable"}</span></Link>)}<Link href={`/health?site=${site}&view=speed`} className="text-sm font-semibold text-purple">Website speed <span className="block text-xs font-normal text-muted">{speed ? `${speed.payload.device} lab score ${speed.payload.score ?? "unavailable"} · ${stamp(speed.updatedAt)}` : "Run the first mobile or desktop test"}</span></Link></div></details>;
}

export function NextActions({ site, name, bundle, tasks }: { site: string; name: string; bundle?: DomainLiveBundle | null; tasks: LiveState<ActionData> }) {
  const [finding, setFinding] = useState<SiteFinding | null>(null);
  const urgent = tasks.data?.items.slice(0, 3) ?? [];
  const recs = (bundle?.datasets.recommendations?.data ?? []).filter((rec) => !urgent.some((item) => item.title === rec.title)).sort((a, b) => b.priorityScore - a.priorityScore).slice(0, Math.max(0, 3 - urgent.length));
  const modulePath = (module: string) => /technical|crawl|audit/i.test(module) ? "/health" : /backlink|link/i.test(module) ? "/backlinks" : /content/i.test(module) ? "/content" : /ai/i.test(module) ? "/ai-visibility" : "/keyword-strategy";
  return <><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-lg font-bold">Do these next</h2><Link href={`/action-centre?site=${site}`} className="text-xs font-semibold text-purple">View all work →</Link></div><div className="divide-y divide-border">{urgent.map((item) => <Link key={item.id} href={actionDestination(item).href} className="flex min-h-12 items-start gap-3 px-4 py-3 hover:bg-workspace"><span className={`rounded px-2 py-1 text-xs ${item.severity === "critical" ? "bg-critical/10 text-critical" : "bg-warning/10 text-warning"}`}>{item.severity === "critical" ? "Critical" : "Urgent"}</span><span className="min-w-0"><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-xs text-muted">{item.detail} · {actionDestination(item).label}</span></span></Link>)}{recs.map((rec) => <div key={rec.id} className="px-4 py-3"><div className="flex flex-wrap items-start justify-between gap-2"><Link href={`${modulePath(rec.module)}?site=${site}`} className="text-sm font-semibold hover:text-purple">{rec.title}</Link><button onClick={() => setFinding({ key: `recommended:${rec.id}`.slice(0, 240), title: rec.title, module: rec.module, executionType: /technical/i.test(rec.module) ? "technical_task" : "refresh_brief", priorityScore: rec.priorityScore, pageMode: "site_wide", sourceUrl: `${modulePath(rec.module)}?site=${site}`, evidenceLabel: rec.evidence, sourceEvidence: { recommendationId: rec.id, confidence: rec.confidence, impact: rec.estImpact, collectedAt: bundle?.datasets.recommendations?.provenance.collectedAt } })} className="min-h-8 text-xs font-semibold text-purple">Review action</button></div><p className="mt-1 text-xs text-muted">Impact: {rec.estImpact} · Effort: {rec.effort === "S" ? "Small" : rec.effort === "M" ? "Medium" : "Large"} · Confidence: {rec.confidence}</p><details className="mt-2 text-xs"><summary className="cursor-pointer text-muted">Why this action</summary><p className="mt-2 leading-5">{rec.evidence}</p></details></div>)}{!urgent.length && !recs.length && <p className="px-4 py-3 text-sm text-muted">{tasks.loading ? "Loading priorities…" : "No actionable priorities in the saved evidence. Check data health and collection coverage."}</p>}{tasks.error && <p className="px-4 py-2 text-sm text-critical">Urgent work could not load. <button className="underline" onClick={tasks.refresh}>Retry</button></p>}</div></Card><SiteFindingWorkDrawer finding={finding} siteSlug={site} siteName={name} onClose={() => setFinding(null)} /></>;
}

export function SiteBriefing({ bundle, site }: { bundle?: DomainLiveBundle | null; site: string }) {
  const ds = bundle?.datasets.gsc_page_movers, movers = [...(ds?.data.losses ?? []), ...(ds?.data.gains ?? [])].sort((a, b) => Math.abs(b.change) - Math.abs(a.change)).slice(0, 3);
  return <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold">What changed</h2><Link href={`/performance?site=${site}&view=timeline`} className="text-xs font-semibold text-purple">View change timeline →</Link></div><p className="mt-1 text-xs text-muted">Page-level click changes in the saved comparison · {ds?.provenance.rangeStart ?? "—"} – {ds?.provenance.rangeEnd ?? "—"}. A change is a signal to investigate, not proof of a cause.</p>{movers.length ? <div className="mt-3 grid gap-3 md:grid-cols-3">{movers.map((row) => <Link href={`/pages?site=${site}&page=${encodeURIComponent(row.key)}`} key={row.key} className="rounded-md border border-border p-3"><span className="block truncate text-sm font-semibold" title={row.key}>{row.key.replace(/^https?:\/\/[^/]+/, "") || "/"}</span><span className={`mt-1 block text-sm ${row.change < 0 ? "text-critical" : "text-success"}`}>{row.change > 0 ? "+" : ""}{row.change.toLocaleString()} clicks</span><span className="mt-1 block text-xs text-muted">{row.clicksBefore.toLocaleString()} → {row.clicksNow.toLocaleString()} · Open page evidence</span></Link>)}</div> : <p className="mt-3 text-sm text-muted">No page comparison is available yet. Collect Google data to compare pages.</p>}</Card>;
}
