"use client";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/primitives";
import { analyseContent, type ContentBenchmark } from "@/lib/content-analysis";
import { stamp } from "@/components/command/shared";
import styles from "@/components/command/command.module.css";
export function OptimisationEditor({ id, initial, keywords, initialBenchmarks, onSaved }: { id: string; initial?: { text: string; revision: string }; keywords: string[]; initialBenchmarks?: ContentBenchmark[]; onSaved: () => void }) {
  const [text, setText] = useState(initial?.text ?? ""), [revision, setRevision] = useState(initial?.revision ?? null), [benchmarks, setBenchmarks] = useState(initialBenchmarks ?? []), [urls, setUrls] = useState((initialBenchmarks ?? []).map((b) => b.url).join("\n")), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const analysis = useMemo(() => analyseContent(text, keywords, benchmarks), [text, keywords, benchmarks]);
  async function act(action: "save" | "compare") {
    setBusy(true); setError(""); setMessage("");
    try { const response = await fetch("/api/content-editor", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, action, ...(action === "save" ? { text, revision } : { urls: urls.split("\n").map((s) => s.trim()).filter(Boolean) }) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (body.editor) { setRevision(body.editor.revision); onSaved(); } if (body.benchmarks) setBenchmarks(body.benchmarks); setMessage(action === "save" ? "Draft saved in this content task." : "Comparison evidence saved."); } catch (e) { setError(e instanceof Error ? e.message : "Editor request failed."); } finally { setBusy(false); }
  }
  return <section className="space-y-3 rounded-lg border border-purple/20 bg-purple/5 p-4"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-bold">Content optimisation editor</h3><Button size="sm" variant="primary" disabled={busy} onClick={() => void act("save")}>Save draft</Button></div><p className="text-xs text-muted">Write here using # for a main heading and ## for section headings. Last saved: {stamp(revision)}.</p><textarea aria-label="Content draft" className={`${styles.field} min-h-80 font-normal leading-relaxed`} maxLength={200000} value={text} onChange={(event) => setText(event.target.value)} placeholder="# Page title\n\nWrite your draft…" /><div className="flex flex-wrap gap-3 text-xs"><strong>{analysis.words} words</strong><span>{analysis.readingMinutes} min read</span><span>{analysis.headings.length} headings</span><span>Reading ease: {analysis.readability ?? "100+ English words needed"}</span></div><p className="text-xs text-muted">Reading ease is an approximate English Flesch score. Coverage and comparison topics are editorial prompts, not ranking guarantees.</p><div className="flex flex-wrap gap-2">{analysis.coverage.map((item) => <span key={item.keyword} className={`rounded border px-2 py-1 text-xs ${item.occurrences ? "border-success/20 text-success" : "border-warning/20 text-warning"}`}>{item.keyword} · {item.occurrences} uses{item.inHeading ? " · in heading" : ""}</span>)}</div><details><summary className="cursor-pointer text-xs font-bold text-purple">Compare with competing pages</summary><div className="mt-3 space-y-3"><label className={styles.label}>Public competitor URLs (up to three)<textarea rows={3} className={styles.field} value={urls} onChange={(e) => setUrls(e.target.value)} /></label><Button size="sm" disabled={busy || !urls.trim()} onClick={() => void act("compare")}>Read comparison pages</Button><p className="text-xs text-muted">Uses public HTML headings and word counts. JavaScript-only text may be absent; page length alone is not a target.</p>{benchmarks.map((b) => <div className="text-xs" key={b.url}><a href={b.url} target="_blank" rel="noreferrer" className="break-all text-purple">{b.title || b.url}</a><p className="text-muted">{b.wordCount} words · {stamp(b.capturedAt)}</p></div>)}{analysis.topics.filter((t) => t.missing).map((t) => <p key={t.heading} className="text-xs">Consider covering: {t.heading}</p>)}</div></details>{message && <p role="status" className="text-xs text-success">{message}</p>}{error && <p role="alert" className="text-xs text-critical">{error}</p>}</section>;
}
